### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by inbetweencode** [leewillis77/pay-with-ether#8]
Hi, sorry if this is not the right place for questions...

Interesting project, I may be interested in contributing in the future. I like it that there is no gateway smart contract in between.

**Questions for now:**

How reliable (do you think) is the service of https://www.paywithether.com at this time.

Any possibility I can test on the ropsten network? (Or is that dependent on the paywithether API (not your service))

What does this mean exactly:
"Data is unnecessary if the payment is exact."

What happens if data (the extra 'Blockchain' field) isn’t sent. Will the transaction just fail after 50 min.?
Is there anything that will prevent me from manually reviving that order? (I also collect the sending ETH address from buyer, so I have another way of checking the transaction).

How is the transaction status pushed/pulled to my website? WP-REST API, wp_cron?

Why have you chosen for the data field, what data is stored in the data field? (or is it simply a unique hash). Have you chosen this because sender + receiving address + amount is not enough to pinpoint a unique transaction?

**Questions for later:**

Would it be feasible to create our own system for monitoring the blockchain (instead of relying on paywithether.com)?
I imagine using AJAX on the order-received page intermittently check the blockchain.

Great stuff!

**Comment by porridj** [comment]
Hey Christophe,

Thanks for your interest in the PWE plugin and service.

I'm one of the guys that runs the Pay With Ether service, and while we've hit a couple of small issues since we started over a year ago, it has been running fantastically for over 6 months now.

Currently the automated service is only on the main network, however you'll be able to use the plugin without the API on any network as you are manually updating the transaction yourself, we've been asked a few times about test networks and ERC20 transaction checking, so they're on the roadmap but not in the near future unfortunately due to the sheer amount of time it takes to make servers reliable.

"Data is unnecessary if the payment is exact." <-- This means that we are using dust as a method of verifying the transaction for systems such as Coinbase, where as previously we were using data for use with MEW etc. (I hope that makes sense, it's coming from me, the least technical member of the team!)

If the data isn't sent and the payment isn't exact, then yes the payment will time out and fail after 50 minutes.

I'm not 100% sure on how the status is sent... let me get back to you on that one.

The data is just a unique hash which is based on order ID. It was the only option that satisfied all the requirements.

It certainly would be possible for you to create your own version of this plugin that connects with your own system for monitoring the ethereum blockchain, however by the time you factor in your time and the server costs for running it all, then the service that is already there might work out the more viable option. Always worth looking into though, just incase.

We have a long list of improvements and additions to make to the automated service, so all recommendations are certainly welcome but may not be put at the top of the list.

Any other questions please feel free to ask and I'll do my best to answer them

Cheers :)

**Comment by christophedejonge** [comment]
I have some trouble getting paywithether to confirm my payments (I transferred between both my accounts). Do I need to open up something in WooCommerce? I use WooCommerce 3.4.1

**Comment by christophedejonge** [comment]
In the debug log I only get:

```
06-01-2018 @ 18:34:41 - Verifying API connection, received code : 200
06-01-2018 @ 18:34:41 - Verifying API connection, received response : 
```

**Comment by porridj** [comment]
Hey Christophe. It SHOULD be working fine. Let me do some tests and I'll get back to you as soon as possible.

**Comment by porridj** [comment]
There is an issue, Tom is just looking into it at the moment

**Comment by leewillis77** [comment]
Closed due to date. If you're having problems with the paywithether.com auto verification service, please contact them for support : https://www.paywithether.com/get-in-touch/
